# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/ip/clk_wiz_01/clk_wiz_01.xci
# IP: The module: 'clk_wiz_01' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/ip/clk_wiz_01/clk_wiz_01_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_01'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/ip/clk_wiz_01/clk_wiz_01.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_01'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/ip/clk_wiz_01/clk_wiz_01_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_01'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/ip/clk_wiz_01/clk_wiz_01.xci
# IP: The module: 'clk_wiz_01' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/ip/clk_wiz_01/clk_wiz_01_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_01'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/ip/clk_wiz_01/clk_wiz_01.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_01'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/ip/clk_wiz_01/clk_wiz_01_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_01'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
