# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/bd/design_1/ip/design_1_axis_i2s_wrapper_0_0/design_1_axis_i2s_wrapper_0_0.xci
# IP: The module: 'design_1_axis_i2s_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/ip/clk_wiz_01/clk_wiz_01.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_01 || ORIG_REF_NAME==clk_wiz_01} -quiet] -quiet

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/bd/design_1/ip/design_1_axis_i2s_wrapper_0_0/design_1_axis_i2s_wrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_i2s_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/bd/design_1/ip/design_1_axis_i2s_wrapper_0_0/design_1_axis_i2s_wrapper_0_0.xci
# IP: The module: 'design_1_axis_i2s_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/ip/clk_wiz_01/clk_wiz_01.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_01 || ORIG_REF_NAME==clk_wiz_01} -quiet] -quiet

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/bd/design_1/ip/design_1_axis_i2s_wrapper_0_0/design_1_axis_i2s_wrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_i2s_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
