# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_1/design_1_FFT_wrapper_0_1.xci
# IP: The module: 'design_1_FFT_wrapper_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_1/design_1_FFT_wrapper_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FFT_wrapper_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_1/design_1_FFT_wrapper_0_1.xci
# IP: The module: 'design_1_FFT_wrapper_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/bzhao30/ENGS128/Lab4/hw/hw.srcs/sources_1/ip/xfft_0/xfft_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# XDC: /home/bzhao30/ENGS128/Lab4/hw/hw.gen/sources_1/bd/design_1/ip/design_1_FFT_wrapper_0_1/design_1_FFT_wrapper_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FFT_wrapper_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
